# -*- coding: utf-8 -*-
"""Project AI 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ct03rGyyPXwWp3iafVq29fLLJFP1awSG
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ======================================================
# 1. Activation Functions
# ======================================================
def sigmoid(z):
    # Clipped to handle extreme values safely during training
    return 1 / (1 + np.exp(-np.clip(z, -20, 20)))

def sigmoid_derivative(a):
    # a = sigmoid(z)
    return a * (1 - a)


# ======================================================
# 2. Data Loading & Preprocessing (Phase 2)
# ======================================================
df = pd.read_csv('heart.csv').dropna()
print(f"Data Loaded: {df.shape[0]} rows, {df.shape[1]} columns.")

X_raw = df.drop(columns=['target']).values
y = df['target'].values.reshape(-1, 1)

# Extract precise min and max constraints from the real dataset
feat_min, feat_max = X_raw.min(axis=0), X_raw.max(axis=0)
X_scaled = (X_raw - feat_min) / (feat_max - feat_min)

# Manual 80/20 Shuffled Train-Test Split
np.random.seed(42)
indices = np.arange(len(X_scaled))
np.random.shuffle(indices)
split = int(0.8 * len(indices))

X_train, X_test = X_scaled[indices[:split]], X_scaled[indices[split:]]
y_train, y_test = y[indices[:split]], y[indices[split:]]


# ======================================================
# 3. Simple Neural Network Structure (Phase 3)
# ======================================================
class SimpleNeuralNetwork:
    def __init__(self, input_dim, hidden_dim, output_dim, lr=0.6):
        np.random.seed(42)
        # Xavier-like random weight initialization
        self.W1 = np.random.randn(input_dim, hidden_dim) * np.sqrt(1.0 / input_dim)
        self.b1 = np.zeros((1, hidden_dim))
        self.W2 = np.random.randn(hidden_dim, output_dim) * np.sqrt(1.0 / hidden_dim)
        self.b2 = np.zeros((1, output_dim))
        self.lr, self.loss_history, self.acc_history = lr, [], []

    def forward(self, X):
        # Hidden layer
        self.a1 = sigmoid(np.dot(X, self.W1) + self.b1)
        # Output layer
        self.a2 = sigmoid(np.dot(self.a1, self.W2) + self.b2)
        return self.a2

    def backprop(self, X, y_true):
        m = X.shape[0]
        
        # -------- Output layer calculation --------
        dZ2 = (self.a2 - y_true) * sigmoid_derivative(self.a2)
        dW2 = np.dot(self.a1.T, dZ2) / m
        db2 = np.sum(dZ2, axis=0, keepdims=True) / m

        # -------- Hidden layer calculation --------
        dZ1 = np.dot(dZ2, self.W2.T) * sigmoid_derivative(self.a1)
        dW1 = np.dot(X.T, dZ1) / m
        db1 = np.sum(dZ1, axis=0, keepdims=True) / m

        # -------- Gradient descent updates --------
        self.W2 -= self.lr * dW2; self.b2 -= self.lr * db2
        self.W1 -= self.lr * dW1; self.b1 -= self.lr * db1

    def predict(self, X):
        return (self.forward(X) >= 0.5).astype(int)

    def accuracy(self, X, y_true):
        return np.mean(self.predict(X) == y_true)

    def fit(self, X, y, epochs=2500, print_every=500):
        for epoch in range(1, epochs + 1):
            self.forward(X)
            self.backprop(X, y)
            
            loss = np.mean((self.a2 - y) ** 2)
            acc = self.accuracy(X, y)
            
            self.loss_history.append(loss)
            self.acc_history.append(acc)
            
            if epoch % print_every == 0 or epoch == 1:
                print(f"Epoch {epoch:4d} | Loss (MSE): {loss:.5f} | Training Accuracy: {acc * 10
