print("=" * 40)
print("HEART DISEASE PREDICTION SYSTEM")
print("=" * 40)
age = float(input("Enter Age: "))
sex = float(input("Enter Sex (0=Female, 1=Male): "))
cp = float(input("Enter Chest Pain Type (0-3): "))
trestbps = float(input("Enter Resting Blood Pressure: "))
chol = float(input("Enter Cholesterol: "))
fbs = float(input("Enter Fasting Blood Sugar (0/1): "))
restecg = float(input("Enter Resting ECG Result: "))
thalach = float(input("Enter Maximum Heart Rate: "))
exang = float(input("Exercise Induced Angina (0/1): "))
oldpeak = float(input("Enter Oldpeak Value: "))
slope = float(input("Enter Slope Value: "))
ca = float(input("Enter Number of Major Vessels: "))
thal = float(input("Enter Thal Value: "))